### ISSUE TITLE
 Copyright header script needs to be disabled in CI Pipeline for Integration Tests 

### ISSUE THREAD

**Issue by yogeshbdeshpande** [veraison/services#212]
The integration tests when run in CI, checks for Copyright Headers.

Need to disable the same in Integration Tests, as the current Step of Checkout Code:

`/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +d55b0617a90c0a9f522e48d148893958d7900664:refs/remotes/origin/realm-provisioning-v2`

Checks-out assuming a new branch! This detects a Copyright Header for files which have not been modified.!

A change has been done in the `CI Test` via a fix in ci.yml using PR #211 
A similar fix is needed in integration-tests.yml

**Comment by setrofim** [comment]
This problem is actually confined to `handler/`.

Cpyright checks are only run as part of `make test`, and so are not typically triggered during integration tests (`make integ-test`). However, `scheme/common/Makefile` contained a `pre` hook that ran `make -C ../../handler`. Since this did not specify a target, it triggered the default goal of `test`. This causes tests and copyright checks to run for `handler/` when shemes are built (not tested!). That means that the copyright check is triggered during Docker deployment creation in the integration tests pipeline.

The `pre` hook is unncessary (or maybe no longer necessary -- it seems to be inhereted from the old code line and its unclear why it was originally added), and is removed in https://github.com/veraison/services/pull/217

**Comment by setrofim** [comment]
Resolved by https://github.com/veraison/services/pull/217
